"""Writes down what each of the sixteen wall masks needs, derived from the bitmask itself.

Whichever tileset gets bought, somebody has to map its pieces onto `wall-<mask>.png`. Doing that from
memory is how a set ends up with its corners mirrored, and the information needed is not a matter of
opinion -- it follows from `DungeonScenery.WallMask`, which sets a bit when that NEIGHBOUR IS ALSO
WALL. So a bit CLEAR means that side faces open floor and is where the boundary has to be drawn.

Generated rather than typed, so the table cannot drift from the code it describes. Run it after any
change to the mask convention.

Run:  python Tools/mask-reference.py          # prints the table
      python Tools/mask-reference.py --write  # writes TILESET-MAPPING.md
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Must match DungeonScenery.WallMask exactly. A set bit means that neighbour is wall.
BITS = [(1, "N"), (2, "E"), (4, "S"), (8, "W")]


def exposed(mask):
    """Which sides face open floor for this mask, in NESW order."""
    return [side for bit, side in BITS if not mask & bit]


def describe(mask):
    """A plain-English name for the piece this mask needs."""
    open_sides = exposed(mask)
    count = len(open_sides)

    if count == 0:
        return "fully enclosed interior -- never touches floor, pure fill"
    if count == 4:
        return "free-standing pillar -- floor on all four sides"
    if count == 1:
        return f"straight run, floor to the {open_sides[0]} only"
    if count == 3:
        return f"stub, wall continues {''.join(s for _, s in BITS if s not in open_sides)} only"

    a, b = open_sides
    opposite = {("N", "S"), ("E", "W")}
    if (a, b) in opposite:
        return f"corridor wall, floor both {a} and {b}"
    return f"outer corner, floor to the {a} and {b}"


def rows():
    """The sixteen rows, lowest mask first."""
    for mask in range(16):
        yield mask, exposed(mask), describe(mask)


def table():
    """The table as markdown."""
    lines = [
        "| mask | bits set (neighbour is wall) | sides facing floor | piece needed |",
        "|---|---|---|---|",
    ]
    for mask, open_sides, note in rows():
        set_bits = "".join(side for bit, side in BITS if mask & bit) or "none"
        floor_sides = "".join(open_sides) or "none"
        lines.append(f"| `wall-{mask}` | {set_bits} | {floor_sides} | {note} |")
    return "\n".join(lines)


DOC = """# Mapping a bought tileset onto this game's sixteen masks

Generated by `python Tools/mask-reference.py --write`. **Do not edit by hand** — regenerate it, so it
cannot drift from `DungeonScenery.WallMask`.

## The convention

`N=1, E=2, S=4, W=8`, and **a bit is SET when that neighbour is also wall**. So a bit CLEAR means the
side faces open floor, and that is the side whose boundary has to be drawn. Off-grid counts as solid,
so the outermost ring of a dungeon does not sprout edges facing nothing.

This is an **edge** set. Most autotile tooling (Tiled, Blobator, Tilesetter) works in **corner**
sets, which are not interchangeable — a 47-tile blob template will not drop in without a conversion
step. Check which one a pack ships before assuming.

{table}

## After mapping, before believing it

```
python Tools/validate-tileset.py --self-test     # proves the gate can fail
python Tools/validate-tileset.py                 # then run it on the tiles
```

The self-test exists because an earlier version of that gate scored a genuinely correct set *worse*
than the broken one it had just condemned, and that verdict was written into three files before
anyone checked. A gate nobody has calibrated is an opinion with a number attached.

The gate that matters here is **shape**: per side, the luminance gap between tiles where that bit is
SET and tiles where it is CLEAR. A set that ignores the mask scores zero on all four.

## Notes on the two candidates

**Neither mapping below is verified** — no pack has been downloaded, and file lists came from store
pages. Treat them as a starting point and confirm against the actual archive.

- **Szadi Rogue Fantasy Castle** ships PNG *and PSD*, and its previews show inner and outer corners
  resolved. The PSD is the reason to prefer it: pieces can be recomposed rather than only sliced.
- **0x72 `dungeontileset-ii`** names pieces directly — `wall_outer_front`, `wall_outer_top_left`,
  `wall_edge_left/right`, `wall_mid` — which lines up with the "piece needed" column above more
  literally than most packs will.

Both are 16x16. This project imports at **PPU 64** with Point filtering and no compression
(`PixelArtImportPostprocessor`), so decide deliberately whether to scale 16→64 by an integer factor
or to change the project's pixels-per-unit. A non-integer resample destroys exactly what point
filtering preserves.
"""


def main():
    if "--write" in sys.argv:
        path = os.path.join(ROOT, "TILESET-MAPPING.md")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(DOC.format(table=table()))
        print("wrote", path)
    else:
        print(table())

    return 0


if __name__ == "__main__":
    sys.exit(main())
